#jdbc
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/gmall_study?characterEncoding=UTF-8
  #dubbo的配置
  dubbo:
    #dubbo的服务名称
    application: user-service
    #dubbo的服务中心地址
    registry:
      address: 10.56.0.61:2181
      #zookeeper的通讯协议的名称
      protocol: zookeeper
    #dubbo的通讯协议名称
    protocol:
      name: dubbo
    #dubbo的服务的扫描路径
    base-package: com.athome.gmall
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8070
# 日志级别设置
logging:
  level:
    root: debug