server:
  port: 8084
logging:
  level: debug
#dubbo的配置

spring:
  dubbo:
    #dubbo中的服务名称
    application: item-web
    #dubbo的通讯协议名称
    protocol:
      name: dubboo
      #dubbo注册中心的地址
    registry:
      address: 115.28.131.8:2181
      #zookeeper的通讯协议名称
      protocol: zookeeper
      #dubbo服务的扫描路径
    base-package: com.athome.gmall
    #设置超时时间
    consumer:
      timeout: 60000
      #设置是否检查服务是否存在
      check: false
    # 关闭thymeleaf的缓存(热部署)
  thymeleaf:
    cache: false

    # 松校验
    mode: LEGACYHTML5