server:
  port: 8081
logging:
  level: debug
spring:
  dubbo:
    application: manage-web
    registry:
      protocol: zookeeper
      address: 115.28.131.8:2181
    protocol:
      name: dubbo
    base-package: com.athome.gmall
  consumer:
    timeout: 600000
    #设置启动时是否检查服务存在,debug过程中，可以先设置为不检查
    check: false